---

extends: default

ignore: |
  *.temp.yml

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  document-start:
    present: true
    ignore: |
      policies/*
  line-length:
    max: 120
