---
name: CICD Pipeline
on: [push]  # noqa yaml[truthy]
jobs:

  # Yaml code checks
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3
      - name: Run yamllint
        run: yamllint .
