---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur
spec:
  refreshInterval: 10s
  secretStoreRef:
    # This name must match the metadata.name in the SecretStore
    name: conjur
    kind: SecretStore
  data:
    - secretKey: nexus-api-key
      remoteRef:
        key: Conjur_TeamA/nexus-api-key
